name: Build and Release

on:
  push:
    tags: ['v*']
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ${{ github.workspace }}/build

    steps:
    - uses: actions/checkout@v4

    - name: Purge Qt5 (critical step)
      run: |
        sudo apt-get remove -y qt5-default || true
        sudo apt-get autoremove -y

    - name: Install Qt6 and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          qt6-base-dev \
          libvtk9-qt-dev \
          libpcl-dev \
          libglew-dev \
          debhelper

    - name: Configure with Qt6
      run: |
        mkdir -p $BUILD_DIR
        cmake -B $BUILD_DIR -S . \
          -DCMAKE_BUILD_TYPE=Release \
          -DQT_VERSION_MAJOR=6 \
          -DQt5_DIR=Qt5_DIR-NOTFOUND \
          -DVTK_QT_VERSION=6 \
          -DPCL_QT_VERSION=6

    - name: Build
      run: cmake --build $BUILD_DIR --parallel $(nproc)

    - name: Create DEB package
      run: |
        cd $BUILD_DIR
        cpack -G DEB
        echo "DEB_FILE=$(ls *.deb)" >> $GITHUB_ENV

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: "Aligner ${{ github.ref_name }}"
        draft: false
        prerelease: false

    - name: Upload DEB package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.BUILD_DIR }}/${{ env.DEB_FILE }}
        asset_name: ${{ env.DEB_FILE }}