name: Build and Release Ubuntu

on:
  push:
    branches: [main]

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0


    - name: Generate commit hash tag
      id: tag
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        echo "TAG_NAME=commit-$COMMIT_HASH" >> $GITHUB_ENV
        echo "Generated tag: $TAG_NAME"

    - name: Install dependencies
      run: |
      # Добавляем ключ и репозиторий Kitware
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/kitware.list

        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          qtbase5-dev \
          libqt5opengl5-dev \
          libvtk9-dev=9.3.* \
          libvtk9-qt-dev \
          libpcl-dev=9.3.* \
          libpcl-visualization1.14 \
          libglew-dev \
          debhelper
    - name: Проверить версию VTK
      run: |
        echo "Установленная версия VTK:"
        dpkg -l | grep libvtk9
        echo "Пути VTK 9.3:"
        ls /usr/lib/cmake/vtk-9.3  # Должна быть папка vtk-9.3

    - name: Configure and build
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DVTK_DIR=/usr/lib/cmake/vtk-9.3
        cmake --build . --config Release --parallel $(nproc)
        cpack -G DEB

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: aligner-package
        path: build/aligner*.deb

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        name: "Release for ${{ env.TAG_NAME }}"
        files: build/aligner*.deb
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}