name: Build and Release

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ${{ github.workspace }}/build
      QT_PREFIX: /usr/lib/x86_64-linux-gnu/cmake/Qt6

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          qt6-base-dev \
          libvtk9-dev \
          libpcl-dev \
          libglew-dev \
          debhelper

    - name: Configure (with Qt6)
      run: |
        mkdir -p $BUILD_DIR
        cmake -B $BUILD_DIR -S . \
          -DCMAKE_BUILD_TYPE=Release \
          -DQt6_DIR=$QT_PREFIX \
          -DQt5_DIR=Qt5_DIR-NOTFOUND

    - name: Build
      run: cmake --build $BUILD_DIR --parallel $(nproc)

    - name: Create DEB package
      run: |
        cd $BUILD_DIR
        cpack -G DEB
        echo "DEB_FILE=$(ls *.deb)" >> $GITHUB_ENV

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: "Aligner ${{ github.ref_name }}"
        body: "Point cloud alignment tool"

    - name: Upload DEB package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.BUILD_DIR }}/${{ env.DEB_FILE }}
        asset_name: ${{ env.DEB_FILE }}