name: Build and Release Ubuntu

on:
  push:
    branches: [main]

jobs:
  build-and-package:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Для работы git describe

    - name: Generate tag
      id: tag
      run: |
        # Используем текущую дату или хэш коммита для тега
        echo "TAG_NAME=release-$(date +'%Y.%m.%d')" >> $GITHUB_ENV
        # Альтернативно: TAG_NAME=release-$(git rev-parse --short HEAD)

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          qtbase5-dev \
          libqt5opengl5-dev \
          libvtk9-dev \
          libvtk9-qt-dev \
          libpcl-dev \
          libpcl-visualization-dev \
          libglew-dev \
          debhelper

    - name: Build and package
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release --parallel 2
        cpack -G DEB

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}  # Используем сгенерированный тег
        files: build/aligner*.deb
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}