name: Build, Package and Release

on:
  push:
    tags:
      - 'v*' # Trigger for release builds
    branches:
      - main # Trigger for test builds

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ${{ github.workspace }}/build

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          qt6-base-dev \
          libvtk9-dev \
          libpcl-dev \
          libglew-dev \
          debhelper \
          dpkg-dev

    - name: Configure project
      run: |
        mkdir -p $BUILD_DIR
        cmake -B $BUILD_DIR -S . \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH="/usr/lib/x86_64-linux-gnu/cmake/Qt6"

    - name: Build project
      run: |
        cmake --build $BUILD_DIR --parallel $(nproc)

    - name: Generate DEB package
      run: |
        cd $BUILD_DIR
        cpack -G DEB --config CPackConfig.cmake

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: aligner-package
        path: ${{ env.BUILD_DIR }}/aligner-*.deb
        retention-days: 5

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        name: "Release ${{ github.ref_name }}"
        tag_name: ${{ github.ref_name }}
        body: "Automatic release of Aligner ${{ github.ref_name }}"
        draft: false
        prerelease: false
        files: |
          ${{ env.BUILD_DIR }}/aligner-*.deb
